// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUXLyEHtt2KbCRrQl26ItFqpTxAjvbjtI',
    appId: '1:703423188252:web:f28a1fc81555fa200ffed9',
    messagingSenderId: '703423188252',
    projectId: 'fir-crud-87fd5',
    authDomain: 'fir-crud-87fd5.firebaseapp.com',
    storageBucket: 'fir-crud-87fd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNcKhdkwm8jBR-EfhGu8MaM0z5dT_IKI',
    appId: '1:703423188252:android:5a021ef4458a6e3f0ffed9',
    messagingSenderId: '703423188252',
    projectId: 'fir-crud-87fd5',
    storageBucket: 'fir-crud-87fd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVxuzPtz_Cvg1pTWUudBTSkCqUCih1nr4',
    appId: '1:703423188252:ios:1da3667a48b2f2640ffed9',
    messagingSenderId: '703423188252',
    projectId: 'fir-crud-87fd5',
    storageBucket: 'fir-crud-87fd5.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
